import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-glass-blue text-white">
        <div className="flex flex-row items-center justify-between py-4 px-8">
          <img
            src="/vrain.png"
            alt="VRAIN Logo"
            width={200}
            height={200}
            className="mx-auto my-4"
          />
          <img
            src="/upv.png"
            alt="Logo"
            width={200}
            height={200}
            className="mx-auto my-4"
          />
        </div>
        {children}
      </body>
    </html>
  );
}
